### ISSUE TITLE
Application Failing to Compile

### ISSUE THREAD

**Issue by Chammz** [Chammz/chat-app#1]
@bdougie just pushed a commit adding the Firebase SDK along with the package for the reactfire in my npm bundle. I've been looking through the setup documentation and it still looks like my app is generating this error that I attached below. I re-added the code below back to index.js

```
ReactDOM.render(
  <App />,
  document.getElementById('root')
);
``` 

The error below is what I am still getting:
![screen shot 2017-02-05 at 7 08 47 pm](https://cloud.githubusercontent.com/assets/12990121/22633413/0b11d450-ebd6-11e6-8577-50d90b720d21.png)

I tried looking into the node package for firebase admin. Trying to open it up with some failed attempts. It won't let me open up the file in a texteditor for some reason.  Obviously looks like I am missing something when I tried configuring the SDK. Any ideas?

Link to commit diff: https://github.com/Chammz/chat-app/commit/5f4f829dba9b36633dbcf6125b0ad1d5572c7b47

Ref to Reactfire: https://github.com/firebase/reactfire/blob/master/docs/guide.md

Ref to Adding Firebase SDK: https://firebase.google.com/docs/admin/setup

**Comment by bdougie** [comment]
http://stackoverflow.com/questions/41186184/firebase-admin-module-not-found-dns has your answer, but I tried that and it only leads to another error and then another. Basically there are missing modules here. 

you can open an issue here, https://github.com/casetext/firebase-admin/issues
---

I have personally never used react-fire, but actually use the firebase js library directly. I recommend taking a look at my project here, https://github.com/bdougie/BlackNotes/blob/master/App/Lib/Api.js, for an example. This is a React Native project, but it is about the same.

remove firebase admin
```
npm uninstall firebase-admin --save
```

add firebase
```
npm install firebase --save
```

create an [api.js](https://github.com/bdougie/BlackNotes/blob/master/App/Lib/Api.js) in a lib folder, similar to adding rooms, I am adding notes. 

Create a fetchdata method in your App.js component.

```
fetchData() {
   api.getNotes()
     .then((data) => {
       this.setState({
         data: data,
       });
     })
  }
```

Look up how state works in React, this is quite diffent from Angular. https://facebook.github.io/react-native/docs/state.html

Use console.log() to see if data comes back from firebase and let me know if you have questions on any of this.

**Comment by Chammz** [comment]
@bdougie New branch: https://github.com/Chammz/chat-app/tree/cp-2-test
