### ISSUE TITLE
Stuck on attempted fix for closing the userName modal

### ISSUE THREAD

**Issue by Chammz** [Chammz/chat-app#4]
@bdougie I attempted to fix by creating a separate `saveUser` function that would look to see if the username was saved and then attempted to close the modal. My thought on this is that it would check this by making sure the input was not an empty string and then I could reuse the `closeModal` function. 

Am I going about this the wrong way? 

https://github.com/Chammz/chat-app/blob/cp-5-setUsername/src/App.js#L61-L76

**Comment by bdougie** [comment]
That is sort of the correct path, and I encourage to continue to explore. However you don't want to save the cookie, but rather get the cookie.
