### ISSUE TITLE
Error Posting Messages to firebase & Saving the value of the currentRoom Attribute

### ISSUE THREAD

**Issue by Chammz** [Chammz/chat-app#7]
@bdougie 
I've been fiddling around with the code the state of the currentRoom attribute on App.js and I seem to be having no luck. The event that listens for the onClick works and I can confirm that the App does change state, but I am not sure if I am appropriately setting the appropriate value of currentRoom. 

https://github.com/Chammz/chat-app/blob/cp-6-sendMessage/src/App.js#L98-L99

With that, I figure I may be able to borrow that data in sendMesssage.js and set that to the value of the roomID key? 

I was able to put a patch on waiting for the sendMessage component to need a selected room before being able to submit a message, but I think I may have caused another bug when getting this error. `App.js:70 Uncaught TypeError: Cannot convert undefined or null to object`

The error makes sense since it is saying it can't convert the value of currentRoom from null to an object. Are there potential work arounds to this?

**Comment by bdougie** [comment]
The error message is actually coming from line 70. This is because you have no message loading. I believe just add a fallback for no message would get rid of this error:

```js
 const mappedMessages = messages ? Object.keys(messages).map((key) => messages[key]) : []
``` 

also the key should be the room id, so you can set it is as a unique value for the currentRoom attribute.

```js
this.setState({currentRoom: key})}
```

**Comment by Chammz** [comment]
That makes complete sense. I think the last remaining issue is the function that is sending the message data to firebase. When I try to submit a message, it returns: 
`Firebase.child failed: First argument was an invalid path: "/messages/[object Object]". Paths must be non-empty strings and can't contain ".", "#", "$", "[", or "]"`

I looked around a bit and I believe it is either my createMessage function:
``` 
createMessage(data) {
  return store.database().ref(`/messages/${data}`).set(data);
}
``` 
or the handleSubmit function that is causing the issue 
``` 
handleSubmit() {
    const data = {
      content: this.state.input,
      roomID: this.state.currentRoom,
      sentAt: new Date(),
      username: cookie.load("username"),
    }
    this.props.onSubmit(data)
  }
```

According to the error, it doesn't want us to pass in an object or is it something else?

**Comment by bdougie** [comment]
is this line here: 
```
.ref(`/messages/${data}`
```
You are trying to pass an object in a url. I would actually remove the `/${data}`, Firebase will actually create a unique id for you if you leave that off.

**Comment by Chammz** [comment]
Gotcha, that is good to know! Hopefully this is the last issue that pops up for this specific piece, but now the console is throwing 
```
Firebase.set failed: First argument contains undefined in property 'messages.roomID'
```

My thought is that in my constructor function set the initial state of `currentRoom: null`

App.js
```
constructor(props) {
    super(props);
    this.state = {
      messages: [],
      rooms: [],
      showModal: false,
      currentRoom: null,
      username: cookie.load("username") || null
     }
```
My thought on this setup was that I set the initial state to this null value when there is no room selection then, when a room is clicked on line 99:
```
<a onClick={() => this.setState({currentRoom: key})}>
```
state is changed and should be useable when the <sendMessage>component is loaded. State would then just modify the data in the handleSubmit function:

```
handleSubmit() {
    const data = {
      content: this.state.input,
      roomID: this.state.currentRoom,
      sentAt: new Date(),
      username: cookie.load("username"),
    }
    this.props.onSubmit(data)
  }
```
Actually, maybe this wouldnt work in the above function because state does not get passed from the parent component, so would props have to be passed into handleSubmit to get the roomID?
